version: "3.1"

services:
  linkerdb_test:
    image: mariadb:latest
    volumes:
      - ./src/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: linkerdb_test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: test
